services:
  web:
    build:
      context: .
    image: revi
    container_name: revi
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
  database:
    image: mysql:8.0
    container_name: revi_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=revi
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
